94-empty-shell-for-how-it-works
zympl/leeway-website pull request #108
Opened 2023-06-19 13:38 UTC by Adhithyarajan

close #94

2023-06-19 13:54 UTC, ajayesivan commented
@Adhithyarajan I don't see the container in the deployed version. We need output similar to the following screenshot,
<img width="613" alt="Screenshot 2023-06-19 at 19 23 23" src="https://github.com/zympl/leeway-website/assets/19279756/55c84888-8738-4876-b4fe-197d6baf8304">

Please refer Figma for design specifics: https://www.figma.com/file/rd8upWhFjqFRaX4hKTTOh3/leeway?type=design&node-id=1252-1869&t=TLGppqLs8mr4zE1f-4

2023-06-19 16:26 UTC, Adhithyarajan commented
i've done that. but when i tried to push it, it still shows an error.

2023-06-19 16:34 UTC, Adhithyarajan commented
![SAVE_20230619_220334](https://github.com/zympl/leeway-website/assets/99787623/89a42c8b-b72a-40c3-9724-ab77ff1f14e2)

2023-06-19 17:34 UTC, Adhithyarajan commented
i think it is resolved and now you got the PR.

2023-06-20 08:43 UTC, ajayesivan requested changes

2023-06-20 08:43 UTC, ajayesivan commented on public/index.html
> -        <img src="images/img2.png" class="mobile">
The image is not visible in mobile view. Please display this image on screen with width up to 900px.

2023-06-20 08:43 UTC, ajayesivan commented on public/styles.css
> +  }
You don't have to repeat all styles again & again. Instead, you can define all styles in the top level (outside all media quires) and then add a media query that will only work if the screen width is below 900px and hide the `rect` and show the image.

eg:
```css
/* Define all the styles outside media queries*/
.rect {
    width: 270px;
    height: 580.86px;
    margin-left: 60px;
    border: 4px solid #03030F;
    border-radius: 20px;
}

.image-section {
  display: none;
}
  
 /* Show the `rect` when the screen size is below 900px & hide the image */
@media (max-width: 900px) {
  .rect {
    display: none;
  }

  .image-section {
    display: block;
  }
}
```

2023-06-20 16:23 UTC, Adhithyarajan commented
is it okay?

2023-06-21 06:23 UTC, ajayesivan commented on public/styles.css
> +  } */
Please remove commented code if its not required.

2023-06-21 06:23 UTC, ajayesivan commented on public/styles.css
> +  } */
This one also

2023-06-21 06:23 UTC, ajayesivan commented on public/styles.css
> +
*1

2023-06-21 06:23 UTC, ajayesivan commented on public/styles.css
>    }
Instead of writing this twice(*1) you can add a new media query that affects all screens under 900px as suggested in the [previous comment](https://github.com/zympl/leeway-website/pull/108#discussion_r1234941773). Let me know if you have any questions regarding this.

2023-06-21 06:23 UTC, ajayesivan commented on public/styles.css
> +  } */
Remove all commented code if it's not required

2023-06-21 14:39 UTC, ajayesivan approved these changes
LGTM! Nice work @Adhithyarajan 🎉

2023-06-21 15:24 UTC, merged