made navbar sticky and transparent
zympl/leeway-website pull request #84
Opened 2023-06-02 18:42 UTC by Adarshvarghese

i made the navbar sticky and transparent .but when i made navbar sticky, in .header-bar class, justify-content became inactive.

2023-06-02 19:06 UTC, ajayesivan requested changes
Also, use `backdrop-filter: blur` to add background blur to the header.

2023-06-02 19:06 UTC, ajayesivan commented on public/styles.css
> +  justify-content: baseline;
Why did you change it `baseline`?

2023-06-02 19:06 UTC, ajayesivan commented on public/styles.css
> +  position: fixed;
When using `position: fixed` you also need to use properties like `left`, `top` etc. to position the elements sproperly.

Please invest some time to learn about CSS `position` properties & `flexbox`

2023-06-03 13:30 UTC, Adarshvarghese commented on public/styles.css
> +  justify-content: baseline;
sorry,I tried other properties to see the changes and forgot to change it back.

2023-06-03 13:30 UTC, Adarshvarghese commented on public/styles.css
> +  position: fixed;
I will go through  the topics that you mantioned.

2023-06-05 06:13 UTC, ajayesivan requested changes
Good progress @Adarshvarghese. We need to fix a few more things before we can merge this PR.

2023-06-05 06:13 UTC, ajayesivan commented on public/index.html
> +      <div><img src="images/icon.svg" class="icon"></div>
Why do we need a `<div>` here?

2023-06-05 06:13 UTC, ajayesivan commented on public/index.html
> +
Remove this spacing.

2023-06-05 06:13 UTC, ajayesivan commented on public/styles.css
> +  width: 100%;
Add a max-width of 1300px for the header content.

2023-06-05 06:13 UTC, ajayesivan commented on public/styles.css
> +  position: fixed;
Great! Once you have a good idea about the position property please add `left` and `top` properties to position the header correctly and update this PR.

2023-06-05 06:13 UTC, ajayesivan commented on public/styles.css
> +  margin-top: -20px;
Remove this negative margin.

2023-06-05 06:13 UTC, ajayesivan commented on public/styles.css
> +  backdrop-filter: blur(5px);
Change blur to `10px`

Note: In the Figma design you can check the **Inspect** tab to get the correct values for most of the CSS properties.

2023-06-05 06:13 UTC, ajayesivan commented on public/styles.css
> +
We don't need this.

2023-06-05 10:10 UTC, Adarshvarghese commented on public/index.html
> +      <div><img src="images/icon.svg" class="icon"></div>
i tried to move the icon using the div but forgot to undo it.

2023-06-06 06:09 UTC, ajayesivan commented
@Adarshvarghese Still the design and result look different. Please try to make this look similar to the design. If you are having trouble, please let us know.

2023-06-06 17:47 UTC, Adarshvarghese commented
i am facing some trouble at this point.please guide me.

2023-06-06 19:17 UTC, Adarshvarghese commented
![design view](https://github.com/zympl/leeway-website/assets/70517375/c4e37cef-c84e-4f29-bbfe-64d6b378f5a1)
above is the design screenshot 
![scr1](https://github.com/zympl/leeway-website/assets/70517375/437c8e41-7845-4cbb-b724-2de3f3ab6ba1)
this is the view in my device when i commented out left property in header-bar

2023-06-07 07:41 UTC, ajayesivan commented
<img width="1728" alt="Screenshot 2023-06-07 at 12 57 35" src="https://github.com/zympl/leeway-website/assets/19279756/4fc7efdc-ff69-403c-add7-68f4201d7c7c">

This is how it looks in my system.

@Adarshvarghese please refer this: https://codepen.io/Ajay-Sivan/pen/rNQNJyY

2023-06-07 11:21 UTC, Adarshvarghese commented
sure i will refer the link .
the screen shots i attached  was after i commented  out the left property in header-bar .and i did not push that change at that time.that is why i mentioned it in the above messsage. I have pushed the changes now.  
please check again and confirm

2023-06-07 12:42 UTC, ajayesivan commented
@Adarshvarghese Desktop view looks good. Please check and update the mobile view too - https://www.figma.com/file/rd8upWhFjqFRaX4hKTTOh3/leeway?type=design&node-id=550-1309&t=AosDZ8ax8oOd8otX-4

Also, make sure the header looks fine on all screen sizes. You can compare the PR preview build with https://leeway.zympl.xyz

2023-06-07 18:03 UTC, Adarshvarghese commented
i have made the remaining changes according to design of mobile view. 
![img1](https://github.com/zympl/leeway-website/assets/70517375/1ed47f8c-b76b-4758-948a-8d1bd33edf49)
![img2](https://github.com/zympl/leeway-website/assets/70517375/4a2f07fc-6248-4fec-a6ec-c556a7308fa8)

above images are the views in my device after the changes made.

2023-06-07 19:51 UTC, ajayesivan commented on public/app.js
> +    headerBar.style.display="none"
@Adarshvarghese Why do we need to change js in a style-related PR?

2023-06-07 19:55 UTC, ajayesivan commented
Your branch | current production
-|-
![zympl-leeway--pr84-sticky-navbar-h5xhi34g web app_(Pixel 5)](https://github.com/zympl/leeway-website/assets/19279756/cc5526a6-0e6c-478f-98e7-68180e7683e5) | ![leeway zympl xyz_(Pixel 5)](https://github.com/zympl/leeway-website/assets/19279756/be8212e5-483a-4ab5-ad3d-0d371b8312f3)


- leeway logo is missing
- menu icon is on the left. it should be on the right.

2023-06-12 06:41 UTC, ajayesivan commented
@Adarshvarghese Please re-request review once you have updated the PR. Please also resolve the conflicts. If you have any questions let me know.

2023-06-19 13:10 UTC, closed without merging