issuecleared
zympl/leeway-website pull request #87
Opened 2023-06-03 14:24 UTC by Adhithyarajan

I've replaced <hr> with <div> and styled it using CSS.

2023-06-05 06:21 UTC, ajayesivan requested changes
@Adhithyarajan Good start! I have added a few comments.

Please also do the following,
- Change the PR title to something meaningful, eg: Fixed terms and conditions page download section.
- Link the related issue to this PR.

2023-06-05 06:21 UTC, ajayesivan commented on public/index.html
> +            <div class="divider"></div>
This element has no effect in the design please remove it.

2023-06-05 06:21 UTC, ajayesivan commented on public/index.html
> +          </p><div class="divider"></div>
We only need one divider element after every `p` tag. This one looks good. Please move it to the next line for better readability.

2023-06-05 06:21 UTC, ajayesivan commented on public/styles.css
> +  border-top: 1.5px solid #bc1717;
change border size from `1.5px` to `1px` and color to `#E6E6E6`

Please check the Figma **Inspect** tab to get accurate values.

2023-06-05 06:21 UTC, ajayesivan commented on public/styles.css
> +  margin-top: 10px 0;
margin-top only accept a single value.
```suggestion
  margin-top: 10px;
```

2023-06-05 06:21 UTC, ajayesivan commented on public/styles.css
> +  }
We only need to define the `divider` class once.

2023-06-05 11:09 UTC, ajayesivan requested changes

2023-06-05 11:09 UTC, ajayesivan commented on public/styles.css
> +  margin-top: 10px;
Add space before & after the divider, please check figma design for actual values.

2023-06-05 11:09 UTC, ajayesivan commented on .vscode/settings.json
Remove this file from tracking. I think many of you have started using vs code live server. So, add `.vscode` to `.gitignore` file to make sure nothing from that folder gets tracked.

Reference: https://git-scm.com/docs/gitignore

2023-06-06 06:16 UTC, ajayesivan commented on .vscode/settings.json
@Adhithyarajan Please remove this file from tracking.

2023-06-06 06:17 UTC, ajayesivan commented on .vscode/settings.json
@Adhithyarajan Did you update `.gitignore` file?

2023-06-06 07:46 UTC, Adhithyarajan commented on .vscode/settings.json
OK

2023-06-06 07:46 UTC, Adhithyarajan commented on .vscode/settings.json
Yes.

2023-06-06 08:01 UTC, Adhithyarajan commented on public/styles.css
> +  margin-top: 10px;
Can you please explain this issue or give a reference or something coz i've checked figma design but i couldn't get a desired output after replacing the values.

2023-06-06 08:43 UTC, Adhithyarajan commented on public/styles.css
> +  margin-top: 10px;
Can you please explain this issue or give me a reference or something coz i've replaced the values by checking figma but didn't get the desired output.

2023-06-06 10:54 UTC, Adhithyarajan commented on .vscode/settings.json
Can you please check it.

2023-06-06 13:51 UTC, ajayesivan requested changes

2023-06-06 13:51 UTC, ajayesivan commented
@Adhithyarajan Please also link the related issue.

2023-06-06 15:21 UTC, ajayesivan approved these changes
LGTM! Great Work @Adhithyarajan 🎉 

Thanks for the PR. You can go ahead and merge this using the GitHub **Squash & Merge** option.

2023-06-06 15:50 UTC, merged