88 update all text and icon colors to new values
zympl/leeway-website pull request #91
Opened 2023-06-05 17:53 UTC by Gowrisankar1

I have updated all text and icon colors to new values

2023-06-06 06:25 UTC, ajayesivan requested changes
For this task, let's leverage the power of CSS variables. I suggest defining two color variables, text-primary-color and text-secondary-color, and utilizing them throughout the code instead of hardcoding the values. This approach will enhance code maintainability and flexibility.

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

2023-06-06 09:44 UTC, Gowrisankar1 commented
I have done the changes. Please take a look.

2023-06-06 13:58 UTC, ajayesivan requested changes

2023-06-06 13:58 UTC, ajayesivan commented on public/styles.css
> +  color: #d81010;
@Gowrisankar1 Could you please explain this change?

2023-06-06 13:58 UTC, ajayesivan commented on public/styles.css
> +.primary{
Please format your code. You can use[ VScode's inbuild format feature](https://code.visualstudio.com/docs/editor/codebasics#_formatting).

2023-06-06 13:58 UTC, ajayesivan commented on public/terms-and-conditions.html
> +        <p>Download now and start effortlessly tracking your expenses.</p>
Why does this PR have unrelated changes?

2023-06-06 14:03 UTC, ajayesivan commented
@Gowrisankar1 avoid putting the issue number in the PR title.

2023-06-06 14:24 UTC, Gowrisankar1 commented on public/styles.css
> +  color: #d81010;
![IMG20230606195227.jpg](https://github.com/zympl/leeway-website/assets/99948166/b2467333-23c6-4752-8e0d-9e8799ad779f)

2023-06-06 14:36 UTC, ajayesivan commented on public/styles.css
> +  color: #d81010;
Not sure what you meant by the screenshot 🤔

2023-06-06 14:38 UTC, Gowrisankar1 commented on public/styles.css
> +  color: #d81010;
I didn't changed it I was just checking

2023-06-06 14:44 UTC, Gowrisankar1 commented on public/styles.css
> +  color: #d81010;
I changed it.Please take a look

2023-06-07 08:39 UTC, ajayesivan approved these changes
LGTM! Thanks for the PR @Gowrisankar1

Please resolve the conflicts and merge the PR.

2023-06-07 09:11 UTC, Gowrisankar1 commented
Can i squash and merge the PR

2023-06-07 10:17 UTC, ajayesivan commented
> Can i squash and merge the PR

Yep.

2023-06-07 10:24 UTC, merged