configured eslint and prettier.installed and set up husky
zympl/leeway-website pull request #92
Opened 2023-06-05 19:20 UTC by Adarshvarghese

#78 
please check the screenshots
![eslint](https://github.com/zympl/leeway-website/assets/70517375/843bf119-b95b-476b-878f-0f7a9359789e)
![husky](https://github.com/zympl/leeway-website/assets/70517375/ae20ff18-65c0-41d2-b559-2dc10d2050e9)
![eg](https://github.com/zympl/leeway-website/assets/70517375/644de7fd-e7cd-4e93-a021-0b7047d8e714)
 i did not run commands shown in eg because  i think  it is given as an example .please correct me if i am wrong

2023-06-05 21:24 UTC, anjali9265 requested changes
Please add a config file for prettier specifying the following:
 1. Print width of 120
 2. Trailing comma
 3. Tab width of 2 spaces
 4. Semicolon
 5. Single quote as true
 
 Also in the Husky hooks add the check for lint and prettier.

2023-06-07 20:27 UTC, anjali9265 commented on package.json
> +    "eslint-plugin-react": "^7.32.2",
Why do we have eslint-plugin-react package?

2023-06-10 14:29 UTC, Adarshvarghese commented on package.json
> +    "eslint-plugin-react": "^7.32.2",
it was added by mistake.

2023-06-10 14:30 UTC, Adarshvarghese commented on package.json
> +    "eslint-plugin-react": "^7.32.2",
i have removed it and pushed changes.Please let me know if there is anything else to be changed.

2023-06-10 17:55 UTC, anjali9265 requested changes

2023-06-10 17:55 UTC, anjali9265 commented on .eslintrc.json
> +    "plugins": [
Please remove all react-related configurations. We don't need those as our project is purely HTML.

2023-06-12 19:57 UTC, anjali9265 approved these changes

2023-06-13 13:37 UTC, merged