Navbar
zympl/leeway-website pull request #97
Opened 2023-06-12 19:39 UTC by Adarshvarghese

testing a new branch for issue

2023-06-16 18:36 UTC, Adarshvarghese commented
i have made the suggested changes .please have look and let me know if i have missed anything.

2023-06-17 08:43 UTC, ajayesivan requested changes
@Adarshvarghese I have added view comments, please check and update the PR. If you have any questions please let me know.

2023-06-17 08:43 UTC, ajayesivan commented on public/app.js
Please remove the new lines added in this line since it is not required.

2023-06-17 08:43 UTC, ajayesivan commented on public/styles.css
> +  max-width: 1300px;
Remove the `max-width` property from `header-bar`, we already have that in the content wrapper.

2023-06-17 08:43 UTC, ajayesivan commented on public/styles.css
> +  /* left: 0px; */
We need `left` property, please add that back.

2023-06-17 08:43 UTC, ajayesivan commented on public/styles.css
> + }
Please remove this since we don't need a `margin-right` here.

2023-06-17 08:43 UTC, ajayesivan commented on public/styles.css
> +
I'm not sure why you added these. In my view, it's not required. But if you think it's needed could you please explain why we need this?

2023-06-17 08:43 UTC, ajayesivan commented on public/styles.css
> +}
We already have a `.nav-menu` selector in this css file, please move the `z-index` there and remove this part.

2023-06-17 08:43 UTC, ajayesivan commented on public/styles.css
>    width: 18px;
Please remove the `width` and `height` properties from `.menu`, this is affecting the layout. Once we remove these properties we won't need the `margin-right` for `.nav-bar`.

2023-06-17 14:55 UTC, Adarshvarghese commented on public/styles.css
> +
When i gave these properties ,to me it seemed more closer to the design in figma.
There were not much  gap between the menu options in design.
Before giving  the properties in menu-option  , copyright@2023 leeway  was not visible in the bottom.
please let me know whether i have to make any changes.

2023-06-17 16:30 UTC, ajayesivan commented on public/styles.css
> +
Can you share a screenshot with and without this code?

2023-06-18 14:11 UTC, Adarshvarghese commented on public/styles.css
> +
before commenting
.menu-option {
    margin-bottom: 10px;
    padding-bottom: 25px;
  }
  .menu-nav{
    padding-top: 125px;
  }

![before_commenting](https://github.com/zympl/leeway-website/assets/70517375/3a34435f-aea6-4cf9-9d74-ddfced816fd0)


After commenting out  :-


![after_commenting](https://github.com/zympl/leeway-website/assets/70517375/4830c1c7-6b0f-42c5-983e-60613c6862b8)

2023-06-18 14:20 UTC, Adarshvarghese commented on public/styles.css
> +
copyright@2023 leeway  is not visible when  padding is given to menu-nav class  without menu-option class .
I checked again and i think it looks fine without padding-bottom in menu-option class.
please have a look and let me know if there is any change required.

2023-06-18 16:39 UTC, ajayesivan approved these changes
LGTM! Great Work 🎉  @Adarshvarghese!

2023-06-18 16:40 UTC, ajayesivan commented on public/styles.css
> +
Your changes look good. Thanks for sharing the screenshot. I have approved the PR. You can squash & merge`

2023-06-18 16:41 UTC, ajayesivan commented on public/styles.css
> +
After merging this PR, please also close the duplicate PR(#84)

2023-06-19 13:08 UTC, merged